apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source
  steps:
    - name: remove-sources
      image: registry.access.redhat.com/ubi8/ubi
      command:
        - /bin/bash
      args: ['-c', 'rm -rf $(workspaces.source.path)/source']
# Запуск с помощью
# tkn task start cleanup --showlog -w name=source,claimName=tekton-pvc
