apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-and-list-pipe
spec:
  workspaces:
    - name: codebase
  tasks:
    - name: clone
      taskRef:
        name: clone
      workspaces:
        - name: source
          workspace: codebase
    - name: list
      taskRef:
        name: list
      workspaces:
        - name: source
          workspace: codebase
      runAfter:
        - clone
# Запуск с помощью
# tkn pipeline start clone-and-list-pipe -w name=codebase,claimName=tekton-pvc --showlog
