apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
    - ReadWriteOnce
    - ReadOnlyMany
  storageClassName: manual
  hostPath:
    path: '/home/alex/ws'
