apiVersion: v1
kind: ConfigMap
metadata:
  name: colors-conf
data:
  error: "\e[31m"
  info: "\e[34m"
  debug: "\e[32m"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: with-configmap
spec:
  volumes:
    - name: colors
      configMap:
        name: colors-conf
  steps:
    - name: logs-with-color
      image: registry.access.redhat.com/ubi8/ubi-minimal
      volumeMounts:
        - name: colors
          mountPath: /var/colors
      script: |
        echo $(cat /var/colors/info) Logging info
        echo $(cat /var/colors/error) Error info
        echo $(cat /var/colors/debug) Debug info
