apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: results
spec:
  results:
    - name: message
      description: Shared message
  steps:
    - name: write
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - /bin/bash
      args:
        - '-c'
        - echo "Coded message" | base64 > $(results.message.path)
    - name: read
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - /bin/sh
        - '-c'
        - cat $(results.message.path)
