apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: dice-roll-result
spec:
  params:
    - name: sides
      description: Number of sides of the dice
      default: '6'
      type: string
  results:
    - name: dice-roll
      description: Random generated number
  steps:
    - name: generate-random-number
      image: node:16
      script: |
        #!/usr/bin/env node
        const fs = require("fs");
        const max = $(params.sides);
        let randomNumber = Math.floor(Math.random() * max) + 1;
        fs.writeFile("$(results.dice-roll.path)", randomNumber.toString(), () => {
          console.log("Dice rolled");
        });
