apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: die-roll
spec:
  steps:
    - name: greetings
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - /bin/bash
      args: ['-c', 'echo Rolling 6-side dice']
    - name: generating
      image: node:16
      script: |
        #!/usr/bin/env node
        const max = 6;
        let rndNumber = Math.floor(Math.random() * Math.floor(max)) + 1;
        console.log(rndNumber);
