apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: pipeline-task01
spec:
  steps:
    - name: task01
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - /bin/bash
      args: ['-c', 'Hello from first task']
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: hello-pipeline
spec:
  tasks:
    - name: first
      taskRef:
        name: pipeline-task01
