apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sleep-and-log
spec:
  params:
    - name: task-name
      type: string
      default: 'hello'
      description: Message
    - name: time
      type: string
      default: '1'
      description: Time
  steps:
    - name: init01
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - /bin/bash
        - '-c'
        - "echo [$(date '+%d/%m/%Y %T')] - Task $(params.task-name) Started"
    - name: sleep02
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - /bin/bash
        - '-c'
        - sleep $(params.time)
    - name: log03
      image: registry.access.redhat.com/ubi8/ubi-minimal
      command:
        - /bin/bash
        - '-c'
        - "echo [$(date '+%d/%m/%Y %T')] - Task $(params.task-name) Completed"
