apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: param-dice-roll
spec:
  params:
    - name: dice-sides
      type: string
      default: '6'
      description: Number of sides on the dice
  tasks:
    - name: first
      taskRef:
        name: pipeline-task01
    - name: roll
      params:
        - name: sides
          value: '$(params.dice-sides)'
      taskRef:
        name: die-roll-param
