apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: param-dice-roll
spec:
  tasks:
    - name: first
      taskRef:
        name: pipeline-task01
    - name: roll
      params:
        - name: sides
          value: '8'
      taskRef:
        name: die-roll-param
