apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: task-reuse
spec:
  tasks:
    - name: say-hello
      params:
        - name: text
          value: 'Hello world'
      taskRef:
        name: logger
    - name: log-something
      params:
        - name: text
          value: 'Something to log'
      taskRef:
        name: logger
